prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix : <https://mermaid.org/ontomermaid/model/def/>

SELECT (GROUP_CONCAT(?fragment; separator="\n") AS ?mermaidFragment)
WHERE {
  
 ?element :* ?childElement.
 ?childElement :fragment ?fragment
}
ORDER BY ?mermaidFragment


